runtime: java
env: flex

runtime_config:
  jdk: openjdk8
  server: jetty9
  artifact: target/acs-0.0.1-SNAPSHOT.war

handlers:
  - url: /.*
    script: this field is required, but ignored
    secure: always

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

inbound_services:
  - warmup

env_variables:
  JAVA_TOOL_OPTIONS: '-XX:MaxRAM=256m'
  SPRING_SECURITY_USER_NAME: "user"
  SPRING_SECURITY_USER_PASSWORD: "APmay7nFZdtx"
  SPRING_SECURITY_ADMIN_NAME: "admin"
  SPRING_SECURITY_ADMIN_PASSWORD: "$#:P>F:9&#;04k>I"