runtime: java
env: flex

runtime_config:
  jdk: openjdk8
  server: jetty
  artifact: target/acs-0.0.1-SNAPSHOT.war

handlers:
  - url: /.*
    script: this field is required, but ignored
    secure: always

manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

inbound_services:
  - warmup

env_variables:
  JAVA_TOOL_OPTIONS: '-XX:MaxRAM=256m'
  SPRING_PROFILES_ACTIVE: "gcp"
  SPRING_SECURITY_USER_NAME: "user"
  SPRING_SECURITY_USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
  SPRING_SECURITY_ADMIN_NAME: "admin"
  SPRING_SECURITY_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}