spring:
  profiles:
    active: gcp

  datasource:
    url: jdbc:sqlserver://34.95.201.193:1433;database=costacrm;encrypt=true;trustServerCertificate=true;
    username: sqlserver
    password: $#:P>F:9&#;04k>I
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    connectionProperties: cloudSqlInstance=steady-thunder-423317-k2:southamerica-east1:dbacsggl01

  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#    root: debug

server:
  tomcat:
    use-native: false
  port: 8443
  ssl:
    key-store: classpath:acsapp.keystore.p12
    key-store-password: ${{ secrets.SSLKEYSTORE }}
    key-store-type: PKCS12
    key-alias: acsapp
  servlet:
    session:
      cookie:
        secure: true
