spring:
  datasource:
#    url: jdbc:sqlserver://LENOVO-P50\MSSQLSERVER:1433;database=costacrm;encrypt=false;
#    username: sa
#    password: Woden26@ws
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    url: jdbc:sqlserver://34.95.201.193\MSSQLSERVER:1433;database=costacrm;encrypt=true;trustServerCertificate=true;
    username: sqlserver
    password: $#:P>F:9&#;04k>I
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#    root: debug

server:
  tomcat:
    use-native: false
  port: 8443
  ssl:
    key-store: classpath:acsapp.keystore.p12
    key-store-password: Woden26@ws
    key-store-type: PKCS12
    key-alias: acsapp
  servlet:
    session:
      cookie:
        secure: true