steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/steady-thunder-423317-k2/acs-web-app', '.']
    env:
      - 'DOCKER_BUILDKIT=1'

options:
  logging: CLOUD_LOGGING_ONLY
