spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/costacrm
    username: root
    password:

  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
