spring:
  datasource:
    url: jdbc:sqlserver://LENOVO-P50\MSSQLSERVER;database=costacrm;encrypt=false;
    username: sa
    password: Woden26@ws
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
