spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/costacrm
    username: root
    password:

  jpa:
    open-in-view: false

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
