apiVersion: v1
kind: Service
metadata:
  name: augusto-costa-acs-service
spec:
  selector:
    app: augusto-costa-acs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer